from __future__ import annotations

import logging
import os

from qa_platform.core.finding import Finding
from qa_platform.core.schemas import IntegrationResult, QualityGateResult
from qa_platform.integrations.dispatcher import IntegrationTarget

logger = logging.getLogger(__name__)


class GitHubIntegration(IntegrationTarget):
    """Posts PR comments, inline review comments, and commit status checks."""

    name = "github"

    def __init__(self, token: str | None = None) -> None:
        self._token = token or os.environ.get("GITHUB_TOKEN", "")

    def is_configured(self) -> bool:
        return bool(self._token)

    def dispatch(
        self,
        findings: list[Finding],
        gate_result: QualityGateResult,
        scan_metadata: dict,
        config: dict,
    ) -> IntegrationResult:
        pr_number = scan_metadata.get("pr_number")
        repo_url = scan_metadata.get("remote_url", "")
        if not pr_number or not repo_url:
            return IntegrationResult(
                target_name=self.name,
                status="skipped",
                error_message="No PR context",
            )

        owner_repo = self._extract_owner_repo(repo_url)
        if not owner_repo:
            return IntegrationResult(
                target_name=self.name,
                status="skipped",
                error_message="Cannot extract owner/repo",
            )

        try:
            import httpx

            headers = {
                "Authorization": f"token {self._token}",
                "Accept": "application/vnd.github.v3+json",
            }

            # Post summary comment
            summary = self._build_summary(findings, gate_result, scan_metadata)
            httpx.post(
                f"https://api.github.com/repos/{owner_repo}/issues/{pr_number}/comments",
                headers=headers,
                json={"body": summary},
                timeout=30,
            )

            # Post inline comments (top 15 findings)
            commit_sha = scan_metadata.get("commit_sha", "")
            if commit_sha:
                self._post_inline_comments(
                    owner_repo, pr_number, commit_sha, findings[:15], headers
                )

            # Set status check
            if commit_sha:
                state = "success" if gate_result.status == "pass" else "failure"
                httpx.post(
                    f"https://api.github.com/repos/{owner_repo}/statuses/{commit_sha}",
                    headers=headers,
                    timeout=30,
                    json={
                        "state": state,
                        "context": "qa-platform",
                        "description": gate_result.reasoning[:140],
                    },
                )

            return IntegrationResult(target_name=self.name, status="success")
        except Exception as e:
            logger.error("GitHub integration error: %s", e)
            return IntegrationResult(
                target_name=self.name, status="error", error_message=str(e)
            )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _extract_owner_repo(self, url: str) -> str:
        """Handle https://github.com/owner/repo.git and git@github.com:owner/repo.git."""
        url = url.rstrip("/").removesuffix(".git")
        if "github.com/" in url:
            return url.split("github.com/")[-1]
        if "github.com:" in url:
            return url.split("github.com:")[-1]
        return ""

    def _build_summary(
        self,
        findings: list[Finding],
        gate_result: QualityGateResult,
        scan_metadata: dict,
    ) -> str:
        sev = gate_result.severity_counts
        lines = [
            "## QA Platform Review",
            f"**Status**: {gate_result.status.upper()} | **Findings**: {len(findings)}",
            (
                f"Critical: {sev.get('critical', 0)} | "
                f"High: {sev.get('high', 0)} | "
                f"Medium: {sev.get('medium', 0)} | "
                f"Low: {sev.get('low', 0)}"
            ),
            "",
            gate_result.reasoning,
            "",
            "---",
            "*This review was generated by QA Platform. "
            "It identifies and reports -- it does NOT modify code.*",
        ]
        return "\n".join(lines)

    def _post_inline_comments(
        self,
        owner_repo: str,
        pr_number: int | str,
        commit_sha: str,
        findings: list[Finding],
        headers: dict,
    ) -> None:
        import httpx

        for f in findings:
            if not f.file or not f.start_line:
                continue
            body = (
                f"**{f.severity.name}** ({f.confidence.name}): {f.title}\n\n"
                f"{f.explanation}\n\n"
                f"**Recommendation**: {f.recommendation}"
            )
            try:
                httpx.post(
                    f"https://api.github.com/repos/{owner_repo}/pulls/{pr_number}/comments",
                    headers=headers,
                    timeout=30,
                    json={
                        "body": body,
                        "commit_id": commit_sha,
                        "path": f.file,
                        "line": f.start_line,
                        "side": "RIGHT",
                    },
                )
            except Exception as e:
                logger.debug(
                    "Failed to post inline comment for %s:%d: %s",
                    f.file,
                    f.start_line,
                    e,
                )
